_name_or_path:
    value: ""
_wandb:
    value:
        cli_version: 0.23.0
        e:
            5f04icx2tg2p4frtu8smp6npgsqcwapm:
                args:
                    - --cfg-path
                    - configs/latent_memory/gsm8k.yaml
                    - --options
                    - model.model_name
                    - Qwen/Qwen2.5-1.5B-Instruct
                    - model.max_prompt_aug_num
                    - "1"
                    - model.max_inference_aug_num
                    - "5"
                    - model.weaver.model_name
                    - Qwen/Qwen2.5-1.5B-Instruct
                    - model.weaver.prompt_latents_len
                    - "16"
                    - model.weaver.inference_latents_len
                    - "8"
                    - model.trigger.model_name
                    - Qwen/Qwen2.5-1.5B-Instruct
                    - model.trigger.active
                    - "False"
                    - datasets.mode
                    - grpo
                    - run.mode
                    - train
                    - run.train_weaver
                    - "True"
                    - run.train_trigger
                    - "False"
                    - run.train_weaver_method
                    - grpo
                    - run.weaver.sft.per_device_train_batch_size
                    - "1"
                    - run.weaver.sft.per_device_train_batch_size
                    - "1"
                    - run.weaver.sft.bf16
                    - "True"
                    - run.interaction.do_sample
                    - "True"
                    - run.interaction.temperature
                    - "1.0"
                    - run.interaction.max_response_length
                    - "1024"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 72
                cpu_count_logical: 144
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "14638514176"
                email: karimpata3@gmail.com
                executable: /root/miniconda3/envs/memgen/bin/python
                git:
                    commit: cdb80c27a457ae06b86e796ae041d75a8c314c99
                    remote: https://github.com/KANABOON1/MemGen
                gpu: NVIDIA A800-SXM4-80GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-fec1b1d5-80c1-55e7-8885-0550650db5f0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-16d94d25-66ed-44ce-2246-c86fba3fcf29
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-c54f9baf-2cde-a546-6498-79d11ed4bce8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-ab64a0a1-937f-1543-e15a-adf93a45d75d
                host: autodl-container-0mr2y4q0at-a0e6700b
                memory:
                    total: "1081806917632"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
                program: /root/.vscode-server/memgen/MemGen/main.py
                python: CPython 3.10.19
                root: /root/.vscode-server/memgen/MemGen
                startedAt: "2026-02-14T15:55:49.518995Z"
                writerId: 5f04icx2tg2p4frtu8smp6npgsqcwapm
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 1
                - 7
                - 19
                - 66
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.55.4
            "9":
                "1": transformers_trainer
            "12": 0.23.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen2ForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
beta:
    value: 0
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
cache_implementation:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
delta:
    value: null
disable_dropout:
    value: false
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
ds3_gather_for_generation:
    value: true
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
epsilon:
    value: 0.2
epsilon_high:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 300
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generation_batch_size:
    value: 32
generation_kwargs:
    value: null
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 1536
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
importance_sampling_level:
    value: token
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
inference_latents_len:
    value: 8
initializer_range:
    value: 0.02
intermediate_size:
    value: 8960
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 1e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_completions:
    value: false
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: trainer_output/runs/Feb14_23-55-36_autodl-container-0mr2y4q0at-a0e6700b
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
loss_type:
    value: grpo
lr_scheduler_type:
    value: cosine
mask_truncated_completions:
    value: false
max_completion_length:
    value: 512
max_grad_norm:
    value: 1
max_inference_aug_num:
    value: 5
max_length:
    value: 20
max_position_embeddings:
    value: 32768
max_prompt_aug_num:
    value: 1
max_prompt_length:
    value: 1024
max_steps:
    value: -1
max_window_layers:
    value: 21
metric_for_best_model:
    value: loss
min_length:
    value: 0
min_p:
    value: null
model/num_parameters:
    value: 1552834050
model_init_kwargs:
    value: null
model_type:
    value: memgen
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 12
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_completions_to_print:
    value: null
num_generations:
    value: 8
num_hidden_layers:
    value: 28
num_iterations:
    value: 1
num_key_value_heads:
    value: 2
num_return_sequences:
    value: 1
num_train_epochs:
    value: 2
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: results/train/gsm8k/Qwen2.5-1.5B-Instruct/pn=1_pl=16_in=5_il=8_20260214-235528/weaver
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
prompt_latents_len:
    value: 16
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
ref_model_mixup_alpha:
    value: 0.6
ref_model_sync_steps:
    value: 512
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - tensorboard
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
reward_weights:
    value: null
rms_norm_eps:
    value: 1e-06
rope_theta:
    value: 1e+06
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 300
save_strategy:
    value: steps
save_total_limit:
    value: null
scale_rewards:
    value: true
seed:
    value: 42
sep_token_id:
    value: null
shuffle_dataset:
    value: true
skip_memory_metrics:
    value: true
sliding_window:
    value: 32768
steps_per_generation:
    value: 1
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_entropy_quantile:
    value: 1
top_k:
    value: null
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: bfloat16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.55.4
trigger_active:
    value: false
trigger_lora_config:
    value:
        bias: none
        lora_alpha: 32
        lora_dropout: 0.1
        r: 16
        target_modules:
            - q_proj
            - v_proj
        task_type: CAUSAL_LM
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_liger_loss:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
use_transformers_paged:
    value: false
use_vllm:
    value: false
vllm_gpu_memory_utilization:
    value: 0.3
vllm_guided_decoding_regex:
    value: null
vllm_mode:
    value: server
vllm_model_impl:
    value: vllm
vllm_server_base_url:
    value: null
vllm_server_host:
    value: 0.0.0.0
vllm_server_port:
    value: 8000
vllm_server_timeout:
    value: 240
vllm_tensor_parallel_size:
    value: 1
vocab_size:
    value: 151936
wandb_log_unique_prompts:
    value: false
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weaver_lora_config:
    value:
        bias: none
        lora_alpha: 32
        lora_dropout: 0.1
        r: 16
        target_modules:
            - q_proj
            - v_proj
        task_type: CAUSAL_LM
weight_decay:
    value: 0
